name: factor_flutter_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.6.0+1008

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  shimmer: ^2.0.0
  shared_preferences: ^2.0.15
  animate_do: ^2.0.0
  uuid: ^3.0.5
  persian_number_utility: ^1.1.1
#  Desktop FireBase
  firebase_core_desktop: ^0.1.1-dev.2
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.5
  flutter_local_notifications: ^9.1.5
  signature: ^5.0.0
  pdf: ^3.7.1
  syncfusion_flutter_pdfviewer: ^20.2.40-beta
#  native_pdf_view: ^6.0.0+1
#  flutter_pdfview: ^1.2.2
  printing: ^5.9.2
  file_saver: ^0.2.0
#  file_saver:
#    git:
#      url: https://github.com/incrediblezayed/file_saver.git
#      ref: main
  image_picker: ^0.8.4+1
  mime: ^1.0.1
#  flutter_poolakey: ^2.0.1
  persian_datetime_picker: ^2.5.0
  share_plus: ^4.0.7
  path_provider: ^2.0.11
  parse_server_sdk_flutter: ^3.1.0
  dartz: ^0.10.1
  url_launcher: ^6.0.20
  carousel_slider: ^4.0.0
  syncfusion_flutter_charts: ^20.2.40
#  zarinpal: ^1.0.4+1
#  uni_links: ^0.5.1
#  webview_flutter: ^3.0.1
  myket_iap: 1.0.4
  connectivity_plus: ^1.0.1
  barcode_widget: ^2.0.2
#  qrscan: ^0.3.0
  cached_network_image: ^3.2.1
  device_apps: ^2.2.0
#  cafebazaar_market: ^0.9.9
#  cafebazaar_flutter: ^1.0.2
#  idpay_payment_package: ^0.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  iran_appmarket: ^2.0.0






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/png/
    - assets/images/jpg/
    - assets/
    - android/gradle/wrapper/gradle-wrapper.properties

  uses-material-design: true

  fonts:
    - family: IRANSans
      fonts:
        - asset: assets/fonts/iran_sans/IRANSansMobile_Black.ttf
          style: normal
          weight: 900

    - family: IRANSans
      fonts:
        - asset: assets/fonts/iran_sans/IRANSansMobile_Bold.ttf
          style: normal
          weight: 700

    - family: IRANSans
      fonts:
        - asset: assets/fonts/iran_sans/IRANSansMobile_Medium.ttf
          style: normal
          weight: 500

    - family: IRANSans
      fonts:
        - asset: assets/fonts/iran_sans/IRANSansMobile_Light.ttf
          style: normal
          weight: 300

    - family: IRANSans
      fonts:
        - asset: assets/fonts/iran_sans/IRANSansMobile_UltraLight.ttf
          style: normal
          weight: 200

    - family: IRANSans
      fonts:
        - asset: assets/fonts/iran_sans/IRANSansMobile.ttf
          style: normal

